apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: partner-catalog
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: partner-catalog
    app.kubernetes.io/part-of: partner-catalog
  name: partner-catalogt7ve
spec:
  path: /
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: partner-catalog
    weight: null
status: {}
